name: Build and Deploy with Expo

on:
  push:
    branches:
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout code
        uses: actions/checkout@v3

      - name: ⌛ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Install EAS CLI
        run: npm install -g eas-cli

      - name: 🔑 Authenticate with Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Run EAS Build - Android
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # - name: 📦 Run EAS Build - iOS
      #   run: eas build --platform ios --profile production --non-interactive
      #   env:
      #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

     
      # - name: 🧱 Decode play-store.json from Base64
      #   run: |
      #     mkdir -p ./keys
      #     echo "${{ secrets.PLAY_STORE_JSON_BASE64 }}" | base64 -d > ./keys/play-store.json

      # - name: 🚀 Submit Android to Play Store
      #   run: eas submit --latest --platform android --non-interactive
      #   env:
      #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
     

      # - name: 🚀 Submit iOS to TestFlight
      #   run: eas submit -p ios --profile production --non-interactive
      #   env:
      #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
